#cloud-config
repo_update: true
repo_upgrade: all
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDH4ndLz8Jsqg1COiTjiM6yuOwCLC2MQYn8OzTmKn9l5A/DqraLfOo66rFAHKTrdMl1NntHDoE9jh1h0LYF/Eqvv96K4mSbuIzazijY3Njeta08YfAVWcnHPWhmyULH1i3V4iENseHFmXHbYHksIf4mJo4SoH3QI15yyOaEOvtY+/sL9uOHv6Eavx6GPbjMRwe55P2hmNMNG65q5j4j6nPbYrc5LmgkINRLNrrsFXYHgRz2c0jXrTw1UrSuabiNKvf22QbMEP/vEh23tSwJ244Z7+cHAGyThqsn4QnuG02iPcR8/8GUrkpSNAHVsjjIpZmrAucf9CbrtGXdt6u0dJcs2gNEf+dC8iYVbS7uyddMewq+J9JSpNMCmkPhFOf38n0EpiewaPNTrL7W0Zj17C2aCjX8uYvXnmpcXgx5o357gfGhpcGHcZe3v+E2raVuPGE5J/+AIsr5cb6mKqv8Jo4dAVftxXvjAuPBlW6C2JbvBgvfLfqjV8nBy2VFibB6o+U= ubuntu-instance-key
