#cloud-config
repo_update: true
repo_upgrade: all
packages:
  - docker
runcmd:
  - sudo systemctl enable docker
  - sudo service docker start
  - sudo chmod 666 /var/run/docker.sock
  - sudo docker run -p 80:80 nginxdemos/hello

