apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-deployment
  labels:
    app: task3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3
  template:
    metadata:
      labels:
        app: task3
    spec:
      containers:
        - name: task3-app
          image: deplake/devops-for-java-bootcamp-task3-extra:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-db
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
---
apiVersion: v1
kind: Service
metadata:
  name: task3-service
spec:
  type: NodePort
  selector:
    app: task3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30111
