---
services:
  hello-world:
    image: nginxdemos/hello
    deploy:
      mode: replicated
      replicas: 5
  java-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DEVOPS: ${DEVOPS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgresql
  postgresql:
    image: postgres:13.13
    volumes:
      - "postgresql-data:/var/lib/postgresql/data/"
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  postgresql-data:
    driver: local

