---
services:
  hello-world:
    image: nginxdemos/hello
    deploy:
      mode: replicated
      replicas: 5
  java-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DEVOPS: "Sergey Koval override value by compose"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:13.13
    volumes:
      - "postgresql-data:/var/lib/postgresql/data/"
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=task3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  postgresql-data:
    driver: local

